[phases.setup]
nixPkgs = ["ffmpeg", "nodejs_20", "chromium"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/nix/var/nix/profiles/default/bin/chromium"

[start]
cmd = "npm start"
